# Generated by Django 3.2.25 on 2025-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_type', models.CharField(max_length=5)),
                ('allergies', models.TextField()),
                ('medical_conditions', models.TextField()),
            ],
        ),
    ]
