# Generated by Django 3.2.25 on 2025-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.CharField(max_length=255)),
                ('diagnosis_date', models.DateField()),
                ('summary', models.TextField()),
                ('result', models.TextField()),
                ('medical_board', models.TextField()),
            ],
        ),
    ]
